spring:
  application:
    name: eureka-center
server:
  port: 8080
eureka:
  client:
    # 检索服务的时长
    registry-fetch-interval-seconds: 30
    # 是否向注册中心注册自己
    register-with-eureka: false
    # 是否心跳校验
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}
